ea:    
    pop_size: 30
    num_iter: 1000
    sbxdi: 2
    pmdi: 5
    pswap: 0.5
    dimension: 50
    rmp: 0.3
    repeat: 1
    is_test: True

amtea:
    pop_size: 30
    num_iter: 1000
    sbxdi: 2
    pmdi: 5
    pswap: 0.5
    dimension: 50
    repeat: 1
    is_test: True

database:
    host: localhost
    user: root
    password: 'password'
    db: cea
    verbose: false
    method:
        name: VARCHAR(255)

database1:
    host: localhost
    user: root
    password: 'password'
    db: amtea
    verbose: false
    method:
        name: VARCHAR(255)
